// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIGUekDuCrTwcpQlsTXmoFZCO7opSspFI',
    appId: '1:987752711098:web:08fd5a093f2c4ae0b2d383',
    messagingSenderId: '987752711098',
    projectId: 'second-phd4wg',
    authDomain: 'second-phd4wg.firebaseapp.com',
    storageBucket: 'second-phd4wg.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1JBE2YPbhPB6hmWOI1PqJJ1mJyTKLGMY',
    appId: '1:987752711098:android:bcd492c86c4adeecb2d383',
    messagingSenderId: '987752711098',
    projectId: 'second-phd4wg',
    storageBucket: 'second-phd4wg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCukqhyhKPrx-MLR9mUTLgDyNwuGd-aSxs',
    appId: '1:987752711098:ios:780437275cb23189b2d383',
    messagingSenderId: '987752711098',
    projectId: 'second-phd4wg',
    storageBucket: 'second-phd4wg.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCukqhyhKPrx-MLR9mUTLgDyNwuGd-aSxs',
    appId: '1:987752711098:ios:780437275cb23189b2d383',
    messagingSenderId: '987752711098',
    projectId: 'second-phd4wg',
    storageBucket: 'second-phd4wg.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIGUekDuCrTwcpQlsTXmoFZCO7opSspFI',
    appId: '1:987752711098:web:1c3295e36dd1c0c3b2d383',
    messagingSenderId: '987752711098',
    projectId: 'second-phd4wg',
    authDomain: 'second-phd4wg.firebaseapp.com',
    storageBucket: 'second-phd4wg.appspot.com',
  );
}
